---
 - hosts: all
   user: ec2-user
   become: yes
   become_method: sudo
   vars:
     motd_value: "{{ lookup('file', '/etc/motd') }}"
   tasks:
    - name: motd value variable
      debug:
        msg: "motd value is {{ motd_value }}"
